nelmio_api_doc:
    documentation:
        info:
            title: Stefan Test
            description: This is my resolving of the test!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
